// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "58d3fc72-0dc9-4ebf-a798-6d1b14dc1a7a");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1527571944);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1527572064);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1527639984);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1527571824);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1527572304);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1527636504);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1527572424);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1527572184);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.bookmarks.showMobileBookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1527571554);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d2dde4e3-8de4-4862-bce7-0ab32af7a72c}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1527523200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1527587262);
user_pref("browser.onboarding.notification.prompt-count", 8);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1527641816245");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1527643616245");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1527639973517");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1527643573517");
user_pref("browser.search.countryCode", "PH");
user_pref("browser.search.region", "PH");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1527571555");
user_pref("browser.slowStartup.averageTime", 1857);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180517113820");
user_pref("browser.startup.homepage_override.mstone", "60.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1527571559928");
user_pref("devtools.debugger.pending-selected-location", "{\"url\":\"ng:///AppModule/AppComponent.html\",\"sourceId\":\"server1.conn8.child1/source73/originalSource-bfe05d24ab9ff24024b14f93a03ffe81\"}");
user_pref("devtools.debugger.prefs-schema-version", "1.0.3");
user_pref("devtools.debugger.tabs", "[\"ng:///AppModule/AppComponent.html\"]");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_SCREEN_RESOLUTION_ENUMERATED_PER_USER\":\"60.0.1\"}");
user_pref("devtools.toolbox.footer.height", 400);
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "60.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Tue, 15 May 2018 10:57:42 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.getAddons.cache.lastUpdate", 1527571945);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "60.0.1");
user_pref("extensions.lastPlatformVersion", "60.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"4d8f5c1b-0f00-4ec9-b953-9fc9958be716\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1527580061);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1527571597);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180517113820");
user_pref("media.gmp-manager.lastCheck", 1527571596);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1527580061);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "e5b3a12a-61bb-49ab-afb1-759aab7d5b54");
user_pref("services.blocklist.addons.checked", 1527536504);
user_pref("services.blocklist.clock_skew_seconds", 35560);
user_pref("services.blocklist.gfx.checked", 1527536504);
user_pref("services.blocklist.last_etag", "\"1527190982439\"");
user_pref("services.blocklist.last_update_seconds", 1527536504);
user_pref("services.blocklist.onecrl.checked", 1527536504);
user_pref("services.blocklist.pinning.checked", 1527536504);
user_pref("services.blocklist.plugins.checked", 1527536504);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1527580061);
user_pref("toolkit.startup.last_success", 1527571553);
user_pref("toolkit.telemetry.cachedClientID", "f7479655-8a59-4fe1-9b4c-c842b16b7ab5");
user_pref("toolkit.telemetry.previousBuildID", "20180517113820");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
